charmplusplus/charm4py

- charmpy/charmlib_cython.pyx
- charmpy/charmpy.py
- tests/reductions/test_gather.py
When a future is the reduction target, the final call to an entry
method to deliver the result will have 2 arguments: the future ID,
and the reduction result. So, the reducer's postprocess function
has to be called on the 2nd argument (not the first).
> Fixed custom reduction postprocess bug when reduction target is a future

- charmpy/chare.py
- tests/dcopy/test_dcopy.py
- tests/migration/test_migrate.py
- tests/reductions/test_gather.py
- tests/thread_entry_methods/test1.py
- tests/thread_entry_methods/test1_when.py
Chare.gather() is a convenience method, but prevents the 'gather'
name from being used by developers.
Instead, gather should be called by doing:
self.contribute(data, Reducer.gather, target)
> Remove Chare.gather() method to free name for use as entry method

- charmpy/charm.py
- test_config.json
- tests/array_maps/test1.py
- tests/charm_remote.py
- tests/migration/chare_migration.py
- tests/migration/test_migrate.py
The charm object is present in every process and represents the
Charm4py runtime. This patch effectively turns it into a chare, by
creating a Group of CharmRemote objects which act as an interface
to the charm object in every process. The new chare can be
accessed via the 'thisProxy' attribute of 'charm'.
> Allow some methods of charm object to be remotely callable

- charmpy/charm.py
- charmpy/interactive.py
- charmrun/start.py
Launching with charmrun on one host with ++interactive
command-line option will enter an interactive shell. For example:
$ python3 -m charmrun.start +p4 ++interactive
will start an interactive shell using 4 processes. In this mode,
new chare types can be defined and created at run time.
Similarly, interactive mode can also be entered from a python
script by doing:
charm.start(interactive=True)
> Support interactive mode with charmrun on one host

- charm4py/reduction.py
Use of long long for 64-bit datatypes is needed not only on
Windows, but also ARM 32-bit systems like the Raspberry Pi.
> reductions: more robust check to know when to use long long types

- charm4py/chare.py
This is done by fixing __name__ and __qualname__ of proxy methods
which are generated at runtime.
This fix allows sending proxy methods to other chares, to be
used, for example, as callbacks:
Example:
worker_proxy.doWork(self.thisProxy[0].getResult)
def doWork(callback):
result = ...
callback(result)
> Fix (un)pickling of proxy methods (to use as callbacks)

- charm4py/charm.py
Although Python's garbage collector could correctly delete
migrated chares, the presence of cyclical references in some of
the internal members of Chare meant that it could only do
so periodically, using an expensive garbage collection routine.
This patch can thus significantly speed up the process by manually
removing the cyclical references after a chare migrates.
> Fix garbage collection performance bug when migrating chares

- charm4py/threads.py
Will send None to the future in these cases.
> Allow Future.send() and Future.__call__() with no arguments

- charm4py/charmlib/ccharm.pxd
- charm4py/charmlib/charmlib_cffi.py
- charm4py/charmlib/charmlib_cffi_build.py
- charm4py/charmlib/charmlib_ctypes.py
- charm4py/charmlib/charmlib_cython.pyx
They are renamed to CreateCallbackMsg and similar names. This is
to account for the more general purpose of these functions and
the new name in the Charm++ C API.
These functions are called from Charm++ to obtain charm4py
messages directed toward charm4py callbacks.
> charmlib layer: rename CreateReductionTargetMsg functions

- charm4py/chare.py
- charm4py/charmlib/ccharm.pxd
- charm4py/charmlib/charmlib_cffi.py
- charm4py/charmlib/charmlib_cffi_build.py
- charm4py/charmlib/charmlib_ctypes.py
- charm4py/charmlib/charmlib_cython.pyx
- test_config.json
- tests/migration/test_nonmigratables.py
Chares that are part of Arrays are migratable by default. If set
to non-migratable status with setMigratable(False), this indicates
to the Charm++ load balancing framework that they shouldn't be
migrated.
> Added Chare.setMigratable(bool) to indicate migratable status

- examples/particle/particle.py
Charm++ currently starts load balancing as soon as the mainchare
is done, even if there are no array elements. And when array
elements are created, it will call resumeFromSync on them even if
they never called AtSync. This will be fixed in an upcoming
release of Charm++, but for now the solution is to avoid using
updateGlobals when doing load balancing.
> particle example: don't use updateGlobals to avoid Charm++ lb bug

- charm4py/charm.py
This allows adding new custom reducers after charm has started,
for example:
charm.thisProxy.exec('def myreducer(contribs): return None',
ret=1).get()
charm.thisProxy.addReducer(myreducer, ret=1).get()
> Add charm.addReducer entry method

- .travis.yml
The setup.py script needs to determine the version of charm4py by
doing git describe, and a limited clone depth can cause git
describe to fail.
> Fix travis build by removing depth restriction on git clone

- charm4py/charm.py
When the interpreter starts, there can be many objects that need
to be garbage collected. Manually calling collect before the first
chares are created can avoid triggering collection too early and
helps to obtain better performance in some circumstances.
> Call gc.collect() on every process after the runtime initializes

- charm4py/__init__.py
These have been deprecated for a while, in favor of charm.myPe(),
charm.numPes(), exit() and charm.abort()
> Remove CkMyPe, CkNumPes, CkExit, CkAbort globals

- charm4py/chare.py
- charm4py/charm.py
- tests/reductions/allreduce.py
allreduce is now a method of Chare, and has the same signature as
Chare.reduce(), except that a callback is not needed since all the
chares that call allreduce will get a result.
Also, made allreduce non-blocking by returning a future.
Removed charm.barrier(chare) because the same can be achieved
by doing empty allreduce: self.allreduce().get()
> Change allreduce API

- charm4py/charm.py
- charm4py/entry_method.py
- charm4py/threads.py
The msg header should be readonly, to in the future allow passing
the same msg header and arguments (same Python objects) to
multiple local chares in a broadcast or section multicast.
> Don't modify header in Charm.process_em_exec()

- charm4py/charm.py
In some rare cases, objects need to be looked up before their
constructor completes. For example, a threaded constructor
blocks to wait for a message. The PE then receives the message
(the constructor didn't complete because it was blocked).
> Store Group and Array elements before calling their constructor

- charm4py/threads.py
- test_config.json
- tests/when/stencil.py
Previously, the value of a future was deposited from an entry method
of the object to which the future belongs. So the wait queues were
automatically flushed after the resumed thread finishes/pauses.
But after the change that sends futures to CharmRemote, the value
is now deposited from an entry method of CharmRemote, and the wait
queues are not flushed automatically. So we do it manually after
the resumed thread finishes/pauses.
> Fix object wait condition queues not being flushed after future resumed

- charm4py/charm.py
When running Charm4py with MPI comm layer and OpenMPI, we need to
explicitly open libmpi with RTLD_GLOBAL (see dc36dfe). In addition,
when running with PyPy, we need to keep a reference to the opened
library.
> Keep reference to libmpi when running with OpenMPI

- charm4py/threads.py
There are some future-related errors that can be hard to detect.
For example, attempting to reuse futures by sending values to a
future that already received them. If new futures immediately
reuse old future IDs (fid), this can end up sending the value to
a new future, which can lead to weird application errors or
deadlocks.
Instead, this patch gives incremental fids to futures created
on the same PE. When the limit is reached (currently 65535 because
Charm++ normally uses unsigned short for reference numbers carried
in callbacks) it restarts at 1. As such, resending to a used
future will almost certainly trigger a future not found error
instead.
Also, there is no pool so it uses less memory.
> Use incremental future IDs instead of pool, for better error detection

- charm4py/__init__.py
- charm4py/charm.py
- charm4py/entry_method.py
- charm4py/interactive.py
- charm4py/pool.py
- charm4py/threads.py
- tests/benchmark/pingpong.py
- tests/callbacks/callbacks.py
- tests/charm_remote.py
- tests/collections/async_array_creation.py
- tests/collections/proxies_same_name.py
- tests/collections/proxies_same_name_aux.py
- tests/entry_methods/retmodes.py
- tests/exceptions/test.py
- tests/reductions/allreduce.py
- tests/sections/allreduce.py
- tests/sections/constrained_groups.py
- tests/sections/slice.py
- tests/thread_entry_methods/test1.py
- tests/thread_entry_methods/test1_when.py
- tests/thread_entry_methods/test2.py
- tests/thread_entry_methods/threaded_ctors1.py
- tests/thread_entry_methods/threaded_ctors2.py
- tests/when/stencil.py
Threaded entry methods are essentially coroutines. And the term
coroutine is now extended across multiple programming languages
to signify subroutines that cooperatively multitask
(non-preemptive multitasking) and which are usually implemented
using lightweight mechanisms that do not require the usual thread
overhead and synchronization (like locks). All of this applies
to Charm4py threaded entry methods, thus the name change.
> Renamed @threaded to @coro

- charm4py/chare.py
This allows proxies to, for example, be inserted in sets, or be
used as dictionary keys.
> Added __hash__ methods for proxies

- charm4py/interactive.py
InteractiveConsole is a chare (a mainchare). This exposes a
reference to it in the interactive prompt, via the 'self' name.
This allows establishing Channels in the interactive prompt
with remote chares, by:
channel = Channel(self, remote=other_chare)
> Expose reference to InteractiveConsole via 'self' in interactive mode

- charm4py/channel.py
- charm4py/charm.py
- examples/jacobi/jacobi2d.py
- examples/multi-module/main.py
- examples/particle/particle.py
- examples/wave2d/wave2d.py
- test_config.json
- tests/channels/iwait.py
- tests/channels/test2.py
- tests/futures/iwait.py
This is because await is a reserved keyword in Python 3.7
> Rename charm.await() and charm.iawait() to wait() and iwait()

- examples/particle/particle.py
- tests/migration/test_nonmigratables.py
The newly merged load balancing patch prohibits using LBPeriod and AtSync simultaneously, so remove the LBPeriod arguments from examples that use AtSync.
> Remove LBPeriod from examples using AtSync

- docs/install.rst
- setup.py
My impression was that #197 removed Python2 support completely, but this might not be accurate.
> version fixes

- charm4py/charm.py
- charm4py/charmlib/charmlib_cython.pyx
When sending messages that contain numpy arrays of built-in types, it is faster to access ```array.dtype.char``` than it is to access ```array.dtype.name```.  More information about datatypes in numpy can be found [here](https://numpy.org/doc/stable/reference/arrays.dtypes.html#data-type-objects-dtype). This patch adds a check for whether a numpy array contains a built-in type, and if so uses the faster method to obtain the type information. This patch decreases message latency almost 12us (from 35.9us to 24.1us) in a microbenchmark. 
This method of accessing the data type is faster because ```array.dtype.name``` executes additional Python code as it has to access arbitrary Python strings (in the case where custom types are created/used).
> Optimize metadata packing for Numpy arrays of 'builtin' types

- auto_test.py
- charmrun/start.py
- test_config.json
- tests/exec.sh
Fixes #206. Performance analysis and memory debugging tools such as Perf and Valgrind do not currently work with Charm4Py's ```charmrun.start```. This patch enables the use of ```charmrun.start``` with these tools.
> Allow execution under analysis tools

- tests/reductions/logical_ops.py
The numpy datatype `np.bool` was deprecated in [NumPy 1.20](https://numpy.org/doc/stable/release/1.20.0-notes.html). This now causes unrelated Charm4Py build failures in Charm CI. This PR fixes the issue.
> Use native bool type in arrays instead of deprecated np.bool

- setup.py
The automatic build for Charm++ did not work for ARM-based machines, including the new Macs. This fixes the error.
> Fix build for ARM-based Machines

- charm4py/charmlib/charmlib_ctypes.py
- docs/install.rst
- setup.py
had to make a new pr to get rid of the ray commits; my original pr was made before ray was merged.
> fixing build issues on mac

- docs/install.rst
This has changes to the install documentation to only include build methods for Charm4Py that currently work. Also, can someone let me know how to update the readthedocs website after any documentation changes?
> Documentation changes

- charm4py/charmlib/charmlib_cffi_build.py
- setup.py
I'm not sure exactly what internal update caused the autobuild to break on macos14 between nightly build 718 and 719 (speculating that its the xcode update from 15.0 to 15.4, but I have not investigated this), but it causes clang to treat `-Wincompatible-function-pointer-types` as an error by default. 
This compiler flag forces clang to treat this error as a warning, which matches the previous behavior, as seen in nightly build 718.
I can replicate this error (and fix) locally on my mac with xcode/15.4 (must force the cffi build via `export CHARM4PY_BUILD_CFFI=1`).
> Fixing cffi autobuild error (convert error to warning)

- docs/install.rst
Adding a minimal one liner which can be used to test the binary installation. Note that examples in `examples/` cannot be run from the binary installation alone because they are not installed with the `charm4py` library.
> Update docs with test/example info

- examples/sssp/README.rst
- examples/sssp/sssp.py
I added a single-source shortest paths (SSSP) example in Charm4Py. You provide a number of vertices, a number of edges, a random seed, and a source vertex. A graph is automatically generated, and then a parallel Bellman-Ford SSSP algorithm is executed on that graph.
> sssp implementation in charm4py

- docs/reductions-api.rst
Added two paragraphs for the charm4py doc - more about reduce() and contribute()
> Docs - Reductions - added contribute() details

- charm4py/charmlib/charmlib_cython.pyx
This updates PyInt (deprecated) to PyLong for converting to Python integers in Cython.
> change to new cpython api call

- pyproject.toml
This solves a SetuptoolsDeprecationWarning by changing how our software license is defined in pyproject.toml.
> spdx format license
